### PR TITLE
prevent spaces in serialnumber

### PR DESCRIPTION
**Pull request by elibl**
Thanks a lot for your great work! I was able to successfully integrate a "SIGA" system. Only a space at the end of the serialnumber prevented the mqtt entities to come up.

### CODE REVIEW

**Comment by Tertiush** [comment]
Thanks for this, but in the latest release I actually already fixed this. See line 1096 & 1097

**Comment by elibl** [comment]
We definitely had spaces in the entity ids with V2.2.0 which were fixed by the strip.

Looking deeper at your code after the quick fix I suspect
(bad python knowledge)
the lines should be:?
`#Remove spaces to prevent the unique ID having spaces`
`bms_sn = bms_sn.replace(" ", "")`
`pack_sn = pack_sn.replace(" ", "")`

But I would prefer this update, because you already publish on line 686 and I don't know how MQTT reacts on spaces within topics...

Untested though.
-> Don't know when I'll have the next opportunity to test...

**Comment by Tertiush** [comment]
Ah good catch I didn't even realise the earlier publish. Ok I'll push a fix over the weekend, basically moving that space-check into the function.

Thanks

**Comment by elibl** [comment]
Same intention by me:
https://github.com/Tertiush/bmspace/pull/14/commits/9177496567bde697aa255ebfea2bf950197936c9

Thanks though.
Really great implementation to catch this naughty protocol!

**Comment by Tertiush** [comment]
Cool yes will merge and test early over the weekend

**Comment by elibl** [comment]
Finally confirmed working with 2.2.1dev. 

Sorry for the delay. 

No spaces anymore💪

Thanks again for your great work!

**Pull request merged**
